[[questions]]
type = "MultipleChoice"
prompt.prompt = """
以下程序能编译通过吗？

```rust
#[derive(Clone, Copy)]
struct BinaryTreeNode {
    value: i32,
    left_child: Option<Box<BinaryTreeNode>>,
    right_child: Option<Box<BinaryTreeNode>>,
}
```
"""
answer.answer = """
不能编译，因为 `Box` 没有实现 `Copy`，所以 `BinaryTreeNode` 也无法实现 `Copy`。
"""
prompt.distractors = [
"""
可以编译通过。
""",
# 认为 Clone 是像 C++ 的拷贝构造函数，而 unique_ptr 没有，所以 Box 也没有。
"""
不能编译，因为 `Box` 没有实现 `Clone`，所以 `BinaryTreeNode` 不能派生 `Clone`。
""",
# 认为 Clone 类似用户自定义拷贝构造函数，而 Copy 类似默认的拷贝构造函数。
"""
不能编译，因为一个类型只能实现 `Clone` 或 `Copy` 其中之一。
""",
# 套用 C++ 的 rule-of-three，但没有理解其在 Rust 中的适用场景。
"""
不能编译，因为 `BinaryTreeNode` 没有实现 `Drop`，即使实现了 `Clone`。
"""
]
context = """
只有当所有字段都实现了 `Copy`，类型才能实现 `Copy`，就像在 C++ 中，只有所有成员都可平凡拷贝时类型才是可平凡拷贝的。`Box` 没有实现 `Copy`。
"""
id = "ec3c58d9-cb13-4f88-ac67-7c1d5baf46e2"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
这个程序能编译吗？如果不能，原因是什么？

```rust
#[derive(Copy)]
struct Age {
    value: u32,
}

impl Clone for Age {
    fn clone(&self) -> Self {
       Age {
           value: 1 + self.value,
       }
    }
}
```
"""
answer.answer = """
能编译，但以与 `Copy` 不一致的方式实现 `Clone` 并不是好主意。
"""
prompt.distractors = [
# 认为 Clone 类似用户自定义拷贝构造函数，而 Copy 类似默认的拷贝构造函数。
"""
不能编译，因为一个类型只能实现 `Clone` 或 `Copy` 其中之一。
""",
# 没理解 Clone 和 Copy 只是普通 trait。
"""
不能编译，因为必须先派生 `Clone` 才能派生 `Copy`。
""",
# 套用 C++ 的 rule-of-three，但没有理解其在 Rust 中的适用场景。
"""
不能编译，因为 `Age` 没有实现 `Drop`，即使实现了 `Clone`。
"""
]
context = """
虽然 `Copy` 要求实现 `Clone`，但对 clone 的实现没有约束。即使这里的 `Clone` 实现明显有问题，程序依然可以编译通过。
"""
id = "0a4bc647-44c9-4244-9dfc-3002d6abc069"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
以下 C++ 程序最地道的 Rust 翻译是哪一个？

```cpp
struct Vec2 {
    double x;
    double y;
};
```
"""
prompt.distractors = [
"""
```rust
#[derive(Clone)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
""",
"""
```rust
#[derive(Copy)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
""",
"""
```rust
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
"""
]
answer.answer = """
```rust
#[derive(Clone, Copy)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
"""
context = """
C++ 的 `Vec2` 实现了拷贝构造函数，对应 Rust 的 `Clone` trait。同时它也是可平凡拷贝的，对应 Rust 的 `Copy` trait。
"""
id = "4636f71a-599b-46d3-a6e6-e0c35b344140"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
以下 C++ 程序最地道的 Rust 翻译是哪一个？

```cpp
struct Vec2 {
    double x;
    double y;

    Vec2(Vec2& other) : x(other.x), y(other.y) {};
};
```
"""
prompt.distractors = [
"""
```rust
#[derive(Clone, Copy)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
""",
"""
```rust
#[derive(Copy)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
""",
"""
```rust
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
"""
]
answer.answer = """
```rust
#[derive(Clone)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}
```
"""
context = """
C++ 的 `Vec2` 有用户自定义的拷贝构造函数，对应 Rust 的 `Clone` trait。虽然实现与默认 trait 行为一致，但由于是用户自定义实现，因此不再是可平凡拷贝类型，对应 Rust 不实现 `Copy` trait。
"""
id = "c8e3b4da-19a1-42e9-97d4-bbb61dcd5652"
