[[questions]]
type = "MultipleChoice"
prompt.prompt = """
如果在 Rust 中为某个类型实现了 `Drop` trait，还应该实现哪些其他 trait？
"""
prompt.distractors = [
"`Move`",
"`Copy`"
]
answer.answer = [
"`Clone`"
]
id = "cddc736a-b6c3-4f3f-a3a7-b42eb362d650"
