[[questions]]
# 本题考查读者是否理解 trait 虽然通过默认方法提供了一些复用，但并不具备继承的其他特性。特别是，默认方法并不是 BareLogger 的一部分，因此无法像切片等方式访问它。
type = "Tracing"
prompt.program = """
trait Logger {
    fn log(&self, message: &str);

    fn error(&self, message: &str) {
        self.log(&format!("ERROR: {}", message));
    }
}

struct BareLogger;

impl Logger for BareLogger {
    fn log(&self, message: &str) {
        println!("{}", message);
    }

    fn error(&self, message: &str) {
        // 省略了 ERROR: 前缀
        println!("{}", message)
    }
}

fn main() {
    let logger = BareLogger;
    logger.log("a message");
    logger.error("an error");
    <BareLogger as Logger>::log(&logger, "another message");
    <BareLogger as Logger>::error(&logger, "another error");
}
"""
answer.doesCompile = true
answer.stdout = """
a message
an error
another message
another error
"""
context = """
与 C++ 父类不同，默认方法并不是 `BareLogger` 的一部分，即使通过 trait 静态访问也是如此。
"""
id = "2bc058d0-99e4-44e0-9abe-5497b713731e"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
以下程序能否编译？如果不能，原因是什么？

```rust
trait Damageable {
    health: u32;

    fn take_damage(&mut self, damage: u32) {
        self.health = self.health.saturating_sub(damage);
    }
}

impl Damageable for Enemy {}

fn main() {
    let e = Enemy;
    e.take_damage(10);
}
```
"""
prompt.distractors = [
# 误以为 trait 类似于 C++ 抽象类
"""
可以编译。
""",
# 误以为问题出在 trait 的实现方式
"""
不能编译，因为 `Enemy` 实现 `Damageable` 时 `health` 没有初始化。
""",
# 误以为问题出在使用方式而不是定义方式
"""
不能编译，因为在 `main` 中使用 `e` 前，`e.health` 没有初始化。
""",
]
answer.answer = """
不能编译，因为在 Rust 中 trait 不能包含字段。
"""
context = """
trait 只定义接口，可以为某些方法提供默认实现，便于用其他 trait 方法实现部分功能。
"""
id = "78c03495-5d3d-4faf-8375-b9f338a377ff"
