[[questions]]
type = "MultipleChoice"
prompt.prompt = """
以下哪个 Rust 程序是对给定 C++ 程序最符合惯用写法的翻译？
```c++
#include <chrono>
#include <string>

enum class MediaType { Text, Image, Video };

class MediaFile {
public:
  MediaType type;
  union {
    struct {
      std::string language;
      size_t length;
    } text;
    struct {
      size_t height;
      size_t width;
    } image;
    struct {
      size_t height;
      size_t width;
      std::chrono::nanoseconds duration;
    } video;
  };

  // 构造函数省略

  size_t size() const {
    switch (type) {
    case MediaType::Text:
      return text.length;
    case MediaType::Image:
      return image.height * image.width;
    case MediaType::Video:
      return video.height * video.width;
    }
    // 不应到达这里
    return 0;
  }
};
```

所有 Rust 程序都使用如下 `MediaFile` 定义。

```rust
enum MediaFile {
    Text {
        language: String,
        length: usize,
    },
    Image {
        height: usize,
        width: usize,
    },
    Video {
        height: usize,
        width: usize,
        duration: std::time::Duration,
    },
}
```
"""
prompt.distractors = [
# 认为 match 可以像 C++ 那样 fallthrough。
# 实际上这是考察 match 的知识点，而 match 与枚举密不可分。
"""
```rust
impl MediaFile {
    fn size(&self) -> usize {
        match self {
            MediaFile::Text { length, .. } => *length,
            MediaFile::Image { height, width, .. } => // fallthrough
            MediaFile::Video { height, width, .. } => height * width,
        }
    }
}
```
""",
# 认为可以直接访问字段而无需判断类型。
"""
```rust
impl MediaFile {
    fn size(&self) -> usize {
        match self {
            MediaFile::Text { length, .. } => *length,
            _ => self.height * self.width,
        }
    }
}
```
"""
]
answer.answer = """
```rust
impl MediaFile {
    fn size(&self) -> usize {
        match self {
            MediaFile::Text { length, .. } => *length,
            MediaFile::Image { height, width, .. }
            | MediaFile::Video { height, width, .. } => height * width,
        }
    }
}
```
"""
id = "8019115c-c84b-4b79-a18d-d2e83ff984da"
