[[questions]]
type = "MultipleChoice"
prompt.prompt="""
在 Rust 中，以下哪种方式是最符合惯用法地使用如下函数？

```rust
/// 将数据获取到给定的缓冲区中。返回填充的字节数，
/// 或在数据结束时返回 `None`。`buf` 的内容不会被读取。
fn fetch(buf: &mut [u8]) -> Option<usize>
```
"""
prompt.distractors = [
# 认为可以跳过初始化，因为字节不会被读取（就像在 C++ 中一样）。
"""
```rust
let mut buf;

while let Some(count) = fetch(&mut buf) {
    // 使用 buf 中的数据
}
```
""",
# 认为优化器可以让初始化只发生一次，因为注释承诺字节不会被读取。
"""
```rust
loop {
    let mut buf = [0u8; 1024];
    let Some(count) = fetch(&mut buf) else {
        break;
    };
    // 使用 buf 中的数据
}
```
"""
]
answer.answer = """
```rust
let mut buf = [0u8; 1024];

while let Some(count) = fetch(&mut buf) {
    // 使用 buf 中的数据
}
```
"""
id = "5b23f54f-b4a2-46f5-87b4-5551a2c93be8"
