[[questions]]
type = "MultipleChoice"
prompt.prompt = """
为什么在 `clone_from` 中检查自赋值不是 Rust 的惯用做法？
```rust
struct LargeStruct {
    field1: String,
    // ...
    field100: String,
}

impl Clone for LargeStruct {
    fn clone(&self) -> Self {
        Self {
            field1: self.field1.clone(),
            // ...
            field100: self.field100.clone(),
        }
    }

    fn clone_from(&mut self, source: &Self) {
        if std::ptr::eq(self, source) {
            return;
        }

        self.field1.clone_from(&source.field1);
        // ...
        self.field100.clone_from(&source.field100);
    }
}
```
"""
prompt.distractors = [
"""
因为 `std::ptr::mem` 是不安全的 Rust。
""",
"""
因为编译器在优化时会自动添加该检查。
"""
]
answer.answer = """
因为 `self` 是一个可变引用，借用检查器保证了 `source` 不可能是指向同一内存位置的引用。
"""
id = "9f8a464a-6fbb-4352-815a-7a42d162f9fd"

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
在 Rust 中，为什么通常使用合成标识符而不是内存地址来表示对象身份？
"""
prompt.distractors = [
"""
在 Rust 中无法访问内存地址。
""",
"""
比较内存地址需要使用不安全的 Rust。
"""
]
answer.answer = [
"""
合成标识符更容易用于构建自引用结构。
""",
"""
合成标识符避免了使用 `Pin` 防止值被移动的复杂性。
"""
]
id = "d60a321a-3b38-4425-8a9a-6b95fe0e3837"
