[[questions]]
type = "MultipleChoice"
prompt.prompt = """
这个程序能编译吗？如果不能，原因是什么？

```rust
trait Jump {
    // 离地高度（米）
    fn height(&self) -> f64;
}

trait Fly {
    // 离地高度（米）
    fn height(&self) -> f64;
}

struct Pigeon {}

impl Pigeon {
    // 从头到尾的长度（米）
    fn height(&self) -> f64 {
        0.3
    }
}

impl Jump for Pigeon {
    fn height(&self) -> f64 {
        0.0
    }
}

impl Fly for Pigeon {
    fn height(&self) -> f64 {
        5.0
    }
}
```
"""
prompt.distractors = [
"""
无法编译，因为 `Pigeon` 不能同时拥有一个名为 `height` 的固有方法，并实现一个包含同名方法的 trait。
""",
"""
无法编译，因为 `Pigeon` 不能实现两个都包含名为 `height` 方法的 trait。
""",
]
answer.answer = [
"可以编译。"
]
id = "8cebf373-6026-43ed-9364-9fda8ca7fdcd"
